- name: rabbitmq
  hosts: rabbitmq
  become: yes
  tasks:
  - name: configure yum repo
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

  - name: configure yum rabbitmq repos
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

  - name: install rabbitmq
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present
    
  
  - name: install rabbitmq
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: restarted
      enabled: yes

  - name: create user roboshop
    ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

  - name: set permission
    ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"