- name: user component
  hosts: user
  become: yes
  tasks:
  - name: disable and enable nodejs 18 v
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  
  - name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - name:  Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent
    
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download app code
    ansible.builtin.get_url:
      urc: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: extracting the zip file
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
    
  - name: install npm depedency files
    ansible.builtin.command: npm install 
    args:
      chdir: /app

  - name: setup user service client
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: demon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb repo
    ansible.builtin.dnf:
      name:  mongodb-org-shell
      state: present

  - name: get the users count
    ansible.builtin.command:  mongo --host mongodb.devaws14.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: user_count

  - name: load user data
    ansible.builtin.command: mongo --host mongodb.devaws14.online < /app/schema/user.js
    when: user_count.stdout == "0" # keep double quotes


  - name: start and enable user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes

  